[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
LegendDataTypes = {rev = "main", url = "https://github.com/legend-exp/LegendDataTypes.jl.git"}
LegendHDF5IO = {rev = "main", url = "https://github.com/legend-exp/LegendHDF5IO.jl.git"}
SolidStateDetectors = {path = "/home/ritaferi/Phd/SolidStateDetectors/SolidStateDetectors.jl/"}
